### 🎵 LISTAR TODAS LAS CANCIONES
GET http://localhost:8080/api/canciones
Content-Type: application/json

###

### 🔎 BUSCAR CANCIÓN POR ID
GET http://localhost:8080/api/canciones/2
Content-Type: application/json

###

### ➕ AGREGAR UNA NUEVA CANCIÓN
POST http://localhost:8080/api/canciones
Content-Type: application/json

{
  "id": "10",
  "titulo": "Let It Be",
  "artista": "The Beatles",
  "genero": "Rock",
  "anio": 1970,
  "duracion": 4.03
}


### ➕ AGREGAR UNA NUEVA CANCIÓN
POST http://localhost:8080/api/canciones
Content-Type: application/json

{
  "id": "11",
  "titulo": "Yogurcito",
  "artista": "Blessd",
  "genero": "Urbano",
  "anio": 2024,
  "duracion": 3.26
}

###

### ✏️ ACTUALIZAR UNA CANCIÓN EXISTENTE
PUT http://localhost:8080/api/canciones/10
Content-Type: application/json

{
  "id": "10",
  "titulo": "Let It Be (Remastered)",
  "artista": "The Beatles",
  "genero": "Rock",
  "anio": 1970,
  "duracion": 4.05
}

###

### 🗑️ ELIMINAR UNA CANCIÓN POR ID
DELETE http://localhost:8080/api/canciones/10
Content-Type: application/json

###

### 🔍 BUSCAR CANCIONES POR TÍTULO
# Devuelve todas las canciones cuyo título contenga la palabra "Love"
GET http://localhost:8080/api/canciones/buscar?titulo=Love
Content-Type: application/json

###

### 🔍 BUSCAR CANCIONES POR GÉNERO
# Devuelve todas las canciones cuyo género contenga "Rock"
GET http://localhost:8080/api/canciones/buscar?genero=Rock
Content-Type: application/json

###

### 🔍 BUSCAR CANCIONES POR TÍTULO Y GÉNERO (filtro combinado)
# Lógica AND: títulos que contengan "Love" Y género "Pop"
GET http://localhost:8080/api/canciones/buscar?titulo=Love&genero=Pop
Content-Type: application/json

### 🔎 BÚSQUEDA AVANZADA - AND (por defecto)
GET http://localhost:8080/api/canciones/buscar/avanzado?titulo=love&genero=pop
Content-Type: application/json

###

### 🔎 BÚSQUEDA AVANZADA - OR
GET http://localhost:8080/api/canciones/buscar/avanzado?titulo=imagine&artista=queen&op=OR
Content-Type: application/json

###

### 🔎 BÚSQUEDA AVANZADA - RANGO AÑOS
GET http://localhost:8080/api/canciones/buscar/avanzado?anioFrom=1970&anioTo=1980
Content-Type: application/json

###

### 🔎 BÚSQUEDA AVANZADA - COMBINADA (titulo + artista + rango) con OR
GET http://localhost:8080/api/canciones/buscar/avanzado?titulo=love&artista=beatles&anioFrom=1960&anioTo=1975&op=OR
Content-Type: application/json

