### 👥 SEGUIR A OTRO USUARIO
POST http://localhost:8080/api/usuarios/seguir?username=nico&destino=deivid
Authorization: Bearer {{token}}
Content-Type: application/json

###

### 🚫 DEJAR DE SEGUIR A UN USUARIO
POST http://localhost:8080/api/usuarios/dejar-seguir?username=nico&destino=samuel
Authorization: Bearer {{token}}
Content-Type: application/json

###

### LISTAR USUARIOS SEGUIDOS
GET http://localhost:8080/api/usuarios/nico/seguidos
Authorization: Bearer {{token}}
Accept: application/json

###

### 💡 SUGERIR USUARIOS PARA SEGUIR (amigos de amigos)
GET http://localhost:8080/api/usuarios/nico/sugerencias?limite=5
Authorization: Bearer {{token}}
Accept: application/json
